### ISSUE TITLE
Fan Control Issues

### ISSUE THREAD

**Issue by Skates1616** [mwav3/smartthingscode#2]
mwav3, as requested, attached are the live logs for the switch.

Even with the newest update, I can turn on the fan but then all control is lost.  I am unable to change the speed or turn off the fan.  I have tried to capture all functionality tests in the this live log (different fan speeds/trying to turn off the switch/original turn on).  On the app, all changes result in a spinning wheel of death and then the following error message:  "A network or server error occurred.  Try again later."

Also, I noticed with the fan speed changes, the Dimmer % also remained at 0%.

`b2e6b07c-7e24-47c9-bacb-0480356504ec 6:26:17 AM: error groovy.lang.MissingMethodException: No signature of method: script_dth_b85493710d7ab9d6a5790be023ad11e2d4c0f40e96e3bd17508ede193e0025e3.has4Speeds() is applicable for argument types: () values: [] @line 284 (fanEvents)

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:26:17 AM: debug parse() >> zwave.parse(zw device: 1C, command: 2603, payload: 63 )

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:25:54 AM: error groovy.lang.MissingMethodException: No signature of method: script_dth_b85493710d7ab9d6a5790be023ad11e2d4c0f40e96e3bd17508ede193e0025e3.has4Speeds() is applicable for argument types: () values: [] @line 360 (low)

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:25:50 AM: error groovy.lang.MissingMethodException: No signature of method: script_dth_b85493710d7ab9d6a5790be023ad11e2d4c0f40e96e3bd17508ede193e0025e3.has4Speeds() is applicable for argument types: () values: [] @line 284 (fanEvents)

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:25:50 AM: debug parse() >> zwave.parse(zw device: 1C, command: 2603, payload: 63 )

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:25:26 AM: error groovy.lang.MissingMethodException: No signature of method: script_dth_b85493710d7ab9d6a5790be023ad11e2d4c0f40e96e3bd17508ede193e0025e3.has4Speeds() is applicable for argument types: () values: [] @line 364 (medium)

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:25:19 AM: error groovy.lang.MissingMethodException: No signature of method: script_dth_b85493710d7ab9d6a5790be023ad11e2d4c0f40e96e3bd17508ede193e0025e3.has4Speeds() is applicable for argument types: () values: [] @line 284 (fanEvents)

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:25:19 AM: debug parse() >> zwave.parse(zw device: 1C, command: 2603, payload: 63 )

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:24:55 AM: error groovy.lang.MissingMethodException: No signature of method: script_dth_b85493710d7ab9d6a5790be023ad11e2d4c0f40e96e3bd17508ede193e0025e3.has4Speeds() is applicable for argument types: () values: [] @line 368 (high)

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:24:47 AM: error groovy.lang.MissingMethodException: No signature of method: script_dth_b85493710d7ab9d6a5790be023ad11e2d4c0f40e96e3bd17508ede193e0025e3.has4Speeds() is applicable for argument types: () values: [] @line 284 (fanEvents)

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:24:47 AM: debug parse() >> zwave.parse(zw device: 1C, command: 2603, payload: 63 )

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:24:31 AM: error groovy.lang.MissingMethodException: No signature of method: script_dth_b85493710d7ab9d6a5790be023ad11e2d4c0f40e96e3bd17508ede193e0025e3.has4Speeds() is applicable for argument types: () values: [] @line 284 (fanEvents)

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:24:31 AM: debug parse() >> zwave.parse(zw device: 1C, command: 2603, payload: 63 )

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:24:25 AM: debug setLevel >> value: 99

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:24:15 AM: error groovy.lang.MissingMethodException: No signature of method: script_dth_b85493710d7ab9d6a5790be023ad11e2d4c0f40e96e3bd17508ede193e0025e3.has4Speeds() is applicable for argument types: () values: [] @line 284 (fanEvents)

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:24:15 AM: debug parse() >> zwave.parse(zw device: 1C, command: 2603, payload: 63 )

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:24:15 AM: debug parse() >> zwave.parse(zw device: 1C, command: 2603, payload: 63 )

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:23:52 AM: error groovy.lang.MissingMethodException: No signature of method: script_dth_b85493710d7ab9d6a5790be023ad11e2d4c0f40e96e3bd17508ede193e0025e3.has4Speeds() is applicable for argument types: () values: [] @line 360 (low)

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:23:35 AM: error groovy.lang.MissingMethodException: No signature of method: script_dth_b85493710d7ab9d6a5790be023ad11e2d4c0f40e96e3bd17508ede193e0025e3.has4Speeds() is applicable for argument types: () values: [] @line 284 (fanEvents)

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:23:35 AM: debug parse() >> zwave.parse(zw device: 1C, command: 2603, payload: 63 )`

**Comment by Skates1616** [comment]
And this is what happened when I manually turned it off:

`b2e6b07c-7e24-47c9-bacb-0480356504ec 6:29:45 AM: error groovy.lang.MissingMethodException: No signature of method: script_dth_b85493710d7ab9d6a5790be023ad11e2d4c0f40e96e3bd17508ede193e0025e3.has4Speeds() is applicable for argument types: () values: [] @line 284 (fanEvents)

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:29:45 AM: debug parse() >> zwave.parse(zw device: 1C, command: 2003, payload: 00 )

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:29:44 AM: error groovy.lang.MissingMethodException: No signature of method: script_dth_b85493710d7ab9d6a5790be023ad11e2d4c0f40e96e3bd17508ede193e0025e3.has4Speeds() is applicable for argument types: () values: [] @line 284 (fanEvents)

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:29:44 AM: debug parse() >> zwave.parse(zw device: 1C, command: 2603, payload: 00 )

b2e6b07c-7e24-47c9-bacb-0480356504ec 6:29:44 AM: debug parse() >> zwave.parse(zw device: 1C, command: 2603, payload: 00 )`

**Comment by Skates1616** [comment]
I also ran a Z-Wave Tweaker scan for you (hopefully it helps):

`b2e6b07c-7e24-47c9-bacb-0480356504ec 7:51:21 AM: info
Parameter #20: [id:20, scaledConfigurationValue:0, size:1]

b2e6b07c-7e24-47c9-bacb-0480356504ec 7:51:21 AM: info Parameters [21]:
Parameter #0: [id:0, scaledConfigurationValue:0, size:1]
Parameter #1: [id:1, scaledConfigurationValue:0, size:1]
Parameter #2: [id:2, scaledConfigurationValue:0, size:1]
Parameter #3: [id:3, scaledConfigurationValue:0, size:1]
Parameter #4: [id:4, scaledConfigurationValue:0, size:1]
Parameter #5: [id:5, scaledConfigurationValue:0, size:1]
Parameter #6: [id:6, scaledConfigurationValue:0, size:1]
Parameter #7: [id:7, scaledConfigurationValue:0, size:1]
Parameter #8: [id:8, scaledConfigurationValue:0, size:1]
Parameter #9: [id:9, scaledConfigurationValue:0, size:1]
Parameter #10: [id:10, scaledConfigurationValue:0, size:1]
Parameter #11: [id:11, scaledConfigurationValue:0, size:1]
Parameter #12: [id:12, scaledConfigurationValue:0, size:1]
Parameter #13: [id:13, scaledConfigurationValue:0, size:1]
Parameter #14: [id:14, scaledConfigurationValue:0, size:1]
Parameter #15: [id:15, scaledConfigurationValue:0, size:1]
Parameter #16: [id:16, scaledConfigurationValue:0, size:1]
Parameter #17: [id:17, scaledConfigurationValue:0, size:1]
Parameter #18: [id:18, scaledConfigurationValue:0, size:1]
Parameter #19: [id:19, scaledConfigurationValue:0, size:1]

b2e6b07c-7e24-47c9-bacb-0480356504ec 7:51:12 AM: info Association groups [3]:
Association Group #1: [id:1, maxNodesSupported:5, name:Lifeline, nodes:[01]]
Association Group #2: [id:2, maxNodesSupported:5, name:Fan control(Key1), nodes:[]]
Association Group #3: [id:3, maxNodesSupported:5, nodes:[01]]

b2e6b07c-7e24-47c9-bacb-0480356504ec 7:51:07 AM: info Discovery Stats:
Number of association groups discovered: 3 [Print Assoc Groups]
Number of endpoints discovered: 0 [Print Endpoints]
Number of parameters discovered: 21 [Print Parameters]
Number of unique command types received: 8 [Print Commands]
Number of MeterReport types discovered: 0 [Print Sensor]
Number of NotificationReport types discovered: 0 [Print Sensor]
Number of SensorMultilevelReport types discovered: 0 [Print Sensor]

b2e6b07c-7e24-47c9-bacb-0480356504ec 7:51:07 AM: info General Information:
Device Name: Family Room Fan Control
Raw Description: zw:L type:1108 mfr:0063 prod:4944 model:3131 ver:5.22 zwv:4.54 lib:03 cc:5E,86,72,5A,85,59,73,26,27,70,56,2C,2B,7A
Supported Command Classes: [SWITCH_MULTILEVEL (0x26), SWITCH_ALL (0x27), SCENE_ACTIVATION (0x2B), SCENE_ACTUATOR_CONF (0x2C), CRC_16_ENCAP (0x56), ASSOCIATION_GRP_INFO (0x59), DEVICE_RESET_LOCALLY (0x5A), ZWAVEPLUS_INFO (0x5E), CONFIGURATION (0x70), MANUFACTURER_SPECIFIC (0x72), POWERLEVEL (0x73), FIRMWARE_UPDATE_MD (0x7A), ASSOCIATION (0x85), VERSION (0x86)]
Security: Device is not using security.
Manufacturer ID: 0063
Manufacturer Name: null
Product Type ID: 4944
Product ID: 3131
Firmware Metadata: Firmware ID: null, Checksum: null
Application (Firmware) Version: 5.22
Z-Wave Protocol Version: 4.54
Z-Wave Library Type: 03 (Enhanced Slave)
Powerlevel: null
Protection Mode: [ Local: null (null), RF: null (null) ]
Switch_All Mode: 255 (Device is included in the all on/all off functionality.)`

**Comment by mwav3** [comment]
Methods were missing from the code, thanks for these logs.  I added them back in and updated, let me know if its fixed

**Comment by mwav3** [comment]
Closing based on recent updates
