### ISSUE TITLE
2x and 3x tap not registering in Smartthings

### ISSUE THREAD

**Issue by saiajin** [mwav3/smartthingscode#3]
Hi! Great code thank you for this! However the device will not register multiple taps..and therefore cannot trigger. 
In the history it only shows "pushed" and  "held"...
I would really would love to get double tap working!

Thank you!

**Comment by saiajin** [comment]
I should also mention I am using the 2 button GoControl. Thank U!

**Comment by saiajin** [comment]
Hi I see you also just posted about making the Remotec ZRC-90 to work also which I am also waiting to receive.. any advice on where to watch for updates to get these working In SmartThings would be greatly appreciated!!! Thank U!

**Comment by mwav3** [comment]
For double tap to work the hub needs to be added to association group 3 of the device. The code sends association programming to do that at initial install.  However, because this is a battery powered device, if it is "asleep" it won't get the programming and double tap won't work.

I did a code update to send the association command also at preference update in addition to initial install to try and make the association programming go through more often. To try and get double tap working now:

1- apply the code update 

2- wake the remote up by hitting either button so it is ready for programming 

3- go to preferences and toggle "force settings update/refresh"

Let me know if that worked

**Comment by saiajin** [comment]
I'm sorry I'm still kind of a newb with the Device handlers.... How do I apply the update?   I had your code directly pasted for mine...do I need to add your repo instead? 
When I tried to paste Apri's code v 1.2c and try to Publish I get:
×
×startup failed:<br/>script_dth_metadata_fbbe9da1_98c2_44c2_ae00_f8f43531e9c6: 73: unable to resolve class hubitat.zwave.commands.centralscenev1.CentralSceneNotification <br/> @ line 73, column 16.<br/> def zwaveEvent(hubitat.zwave.commands.centralscenev1.CentralSceneNotification cmd) {<br/> ^<br/><br/>script_dth_metadata_fbbe9da1_98c2_44c2_ae00_f8f43531e9c6: 100: unable to resolve class hubitat.zwave.commands.wakeupv2.WakeUpNotification <br/> @ line 100, column 16.<br/> def zwaveEvent(hubitat.zwave.commands.wakeupv2.WakeUpNotification cmd) {<br/> ^<br/><br/>script_dth_metadata_fbbe9da1_98c2_44c2_ae00_f8f43531e9c6: 113: unable to resolve class hubitat.zwave.commands.batteryv1.BatteryReport <br/> @ line 113, column 16.<br/> def zwaveEvent(hubitat.zwave.commands.batteryv1.BatteryReport cmd) { <br/> ^<br/><br/>3 errors<br/>
<img width="1501" alt="Screen Shot 2021-01-16 at 8 44 27 AM" src="https://user-images.githubusercontent.com/71667075/104817638-5de7f580-57d7-11eb-8b60-7d0d506151ba.png">


I had your code pasted directly before:

<img width="1511" alt="Screen Shot 2021-01-16 at 8 51 43 AM" src="https://user-images.githubusercontent.com/71667075/104817762-19108e80-57d8-11eb-8bfe-9c5a4a3ec4a4.png">

Sorry I think I am confused I apologize... please help me step by step if you can....

**Comment by mwav3** [comment]
You can add the repo mwav3 smartthingscode master to be notified of updates. If you add the repo now and then update from repo, it might update your code you copy pasted but sometimes it doesn't find it. Then you need to switch the device back to the generic handler, delete the gandler you pasted, then add again from repo, then assign the device back.

You can also just open the handler you created from copy paste, paste the new code right over it, then hit "save" and make sure "publish" is checked.

If you're having issues let me know where you're stuck and I'll try and post screenshots.

**Comment by saiajin** [comment]
Thank U so much for your help with this. I'm stuck on graveyard shift this weekend and haven't had a chance to try this out yet. But will ASAP and report back.

**Comment by saiajin** [comment]
"You can also just open the handler you created from copy paste, paste the new code right over it, then hit "save" and make sure "publish" is checked."

This worked great!  So currently I see clicked up/down , clicked up/down and Held or Click up/down twice! I'm going to attempt to program actions....

So 2X seems to work but no 3x..but I'm ok with 2 for now!

**Comment by mwav3** [comment]
3x is actually mapped to double tap and hold. Thanks for letting me know 2x is working. Closing issue as it was resolved with the code update.

**Comment by saiajin** [comment]
Got it! Great! Thank you again!
