### ISSUE TITLE
REMOTEC ZRC-90 only shows as one button in Smartthings

### ISSUE THREAD

**Issue by saiajin** [mwav3/smartthingscode#4]
HI, I installed my ZRC-90 using this device handler. In IDE it shows as 8 buttons.....However in the app and the Remote's history it only shows as one button  pressed/doubled pressed or held...as well when I try it with the Smart Lighting app.

Any help would be greatly appreciated!!!

Thank You!

**Comment by mwav3** [comment]
This is a limitation of the new smarthings app. The new app only is capable of showing one button per device.  You have to use webcore or smartlighting to do automations using all buttons.

**Comment by saiajin** [comment]
Ugh... this sounds like I may have wasted my money....
With the Smart lighting Smart App, it’s showing  only as one button with only 1x 2x and hold also....

I  tried  to install WebCore but it gives me error when logging in so I can trouble shoot that....but if it doesn’t work in Smart Lighting is there still a chance it could work in WebCore?

Thank U!

miles@milesreetz.com
773-301-3041

**Comment by saiajin** [comment]
I tried using ABC Child Creator Smart App and it does show 8 buttons but as with any button I try with ABC, only 1x push and hold are available... I tried this smart App with other devices such as the GoControl and it's the same only 2x and hold but Both buttons show. I have seen people using ABC with multiple clicks before.. but I don't know if this also a limitation of the new app.

**Comment by saiajin** [comment]
I think I have webcore functioning... however it also only shows pushed /held for the buttons... double click not available...

**Comment by saiajin** [comment]
Are multiple clicks possible in Hubitat or Home Assistant? Seems like it's time to dump ST!

**Comment by mwav3** [comment]
You're close to getting it working. Webcore only has pushed and held in the default drop down. Double tap on webcore has to be captured by doing an expression and writing in "double".  See screenshot here 
![Screenshot from 2021-01-12 09-00-22](https://user-images.githubusercontent.com/65051965/105636648-1dbbef00-5e37-11eb-9ea4-71ad9aacf8ec.png)

**Comment by mwav3** [comment]
Button captures are a lot of programming in Home assistant.  I have home assistant but still use Smartthings for these zwave devices.

It might work better in hubitat but no experience with it personally. 

I know Smartthings is a pain lately but I would try and make it work first before giving up and startingover. These button devices are the most troublesome, but with some effort can get working.

**Comment by mwav3** [comment]
Smartlighting should let you pick a button number also with all 3 values. Click button number for list of buttons 1-8 and click action under pushed action.

![Screenshot_20210124-113452_SmartThings](https://user-images.githubusercontent.com/65051965/105636894-79d34300-5e38-11eb-82fa-b2fa6e147c78.jpg)

If only showing one button in smartlighting the number of button value may not be updating properly. Try to toggle force settings update/refresh in preferences to update it.

**Comment by saiajin** [comment]
Force update worked and now I can see the button numbers in Smart Lighting! Woo Hoo!!! Thank you so much. Yes I'm hating all these new limitations of the new ST app... I hope something changes soon... I am tempted to try Home Assistant but it sounds like a pain!!!

**Comment by saiajin** [comment]
Thanks for the explanation for WebCore... I see how powerful it can be just a bit more I need to learn with it but I will definitely have to figure it out to control more than just lighting with the remote...
